package scanner

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// providerSource maps a subfinder data source to the environment variables that
// configure it. Most take a single key; a few need two joined with a colon.
type providerSource struct {
	source string // subfinder's name for the source
	env    string // primary env var
	env2   string // optional second var, joined as "first:second"
}

// providerSources is the full set we support. Keys are optional: a source with
// no value is omitted, so subfinder simply does not query it.
var providerSources = []providerSource{
	{source: "dnsdumpster", env: "DNSDUMPSTER_API_KEY"},
	{source: "shodan", env: "SHODAN_API_KEY"},
	{source: "censys", env: "CENSYS_API_ID", env2: "CENSYS_API_SECRET"},
	{source: "securitytrails", env: "SECURITYTRAILS_API_KEY"},
	{source: "netlas", env: "NETLAS_API_KEY"},
	{source: "zoomeye", env: "ZOOMEYE_API_KEY"},
	{source: "quake", env: "QUAKE_API_KEY"},
	{source: "fofa", env: "FOFA_EMAIL", env2: "FOFA_API_KEY"},
	{source: "hunter", env: "HUNTER_API_KEY"},
	{source: "binaryedge", env: "BINARYEDGE_API_KEY"},
	{source: "leakix", env: "LEAKIX_API_KEY"},
	{source: "virustotal", env: "VIRUSTOTAL_API_KEY"},
	{source: "whoisxmlapi", env: "WHOISXMLAPI_API_KEY"},
	{source: "bevigil", env: "BEVIGIL_API_KEY"},
	{source: "intelx", env: "INTELX_HOST", env2: "INTELX_API_KEY"},
	{source: "chaos", env: "CHAOS_API_KEY"},
	{source: "github", env: "GITHUB_TOKEN"},
}

// WriteProviderConfig renders subfinder's provider-config.yaml from the API-key
// environment variables, skipping any source whose key is blank. It returns the
// path written and the source names configured.
//
// Secrets are written to a 0600 file and never logged — callers log only the
// source names.
func WriteProviderConfig(dir string) (string, []string, error) {
	var (
		b          strings.Builder
		configured []string
	)
	b.WriteString("# Generated by the ASM worker from environment variables.\n")
	b.WriteString("# Do not edit: it is rewritten on every worker start.\n")

	for _, ps := range providerSources {
		v1 := strings.TrimSpace(os.Getenv(ps.env))
		if v1 == "" {
			continue
		}
		value := v1
		if ps.env2 != "" {
			v2 := strings.TrimSpace(os.Getenv(ps.env2))
			if v2 == "" {
				// A two-part source is unusable with only half its credentials.
				continue
			}
			value = v1 + ":" + v2
		}
		fmt.Fprintf(&b, "%s:\n  - %s\n", ps.source, value)
		configured = append(configured, ps.source)
	}

	if len(configured) == 0 {
		return "", nil, nil // nothing to write; subfinder uses its free sources
	}

	if err := os.MkdirAll(dir, 0o700); err != nil {
		return "", nil, err
	}
	path := filepath.Join(dir, "subfinder-providers.yaml")
	if err := os.WriteFile(path, []byte(b.String()), 0o600); err != nil {
		return "", nil, err
	}
	sort.Strings(configured)
	return path, configured, nil
}
